<script>
function fun() {

    return new Promise(function(respoonse,reject) {

setTimeout(()=>{
const err=true;
if(!err){
    console.log("tq for resolving ur promiss")
    respoonse();
}else{
    console.log("very bad u did not solve ur promiss")
    reject();
}

},2000)
    })
}
fun().then(function() {
    console.log("wow magical resove promiss")
}).catch(function() {
    console.log("y did u not full fill promiss");
})
//console.log()

</script>
